Allow registering `OutputFormats` without file extension
ronin-rb/ronin-core pull request #58
Opened 2024-08-31 16:27 UTC by AI-Mozi

2024-08-31 23:21 UTC, postmodern requested changes
I realized later this will require changing how `infer_from(path)` works. Maybe it might be easier to have `ext` default to an empty String, since `File.extname('foo') # => ''`.

2024-09-01 16:34 UTC, moozzi commented
But `''` will be used for few different output formats..

2024-09-01 21:59 UTC, postmodern commented
@AI-Mozi hmm yeah. We should keep `register :dir,    '',        Dir` that way `ronin-recon run --output path/to/dir` will select the `OutputFormats::Dir` output format, but `Archive`/`GitArchive` should not specify a file extension and would need to be specified explicitly (ex: `--output-format archive` or `--output archive:path/to/dir`).

2024-09-01 22:51 UTC, postmodern approved these changes

2024-09-01 22:51 UTC, merged